openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API for user signup and signin, integrated with better-auth.com.

servers:
  - url: /api/auth
    description: Authentication API Base Path

paths:
  /signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address.
                  example: "student@example.com"
                password:
                  type: string
                  format: password
                  description: User's chosen password.
                software_background:
                  type: object
                  description: User's software expertise/experience.
                  example: { "languages": ["Python", "JavaScript"], "frameworks": ["React"] }
                hardware_background:
                  type: object
                  description: User's hardware familiarity.
                  example: { "robot_platforms": ["Unitree Go2"], "sensors": ["Intel RealSense"] }
              required:
                - email
                - password
                - software_background
                - hardware_background
      responses:
        '201':
          description: User successfully registered.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    format: uuid
                  message:
                    type: string
                    example: "User registered successfully."
        '400':
          description: Invalid input or user already exists.
        '500':
          description: Internal server error.

  /signin:
    post:
      summary: Authenticate an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address.
                  example: "student@example.com"
                password:
                  type: string
                  format: password
                  description: User's password.
              required:
                - email
                - password
      responses:
        '200':
          description: User successfully authenticated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    format: uuid
                  token:
                    type: string
                    description: Authentication token.
        '401':
          description: Invalid credentials.
        '500':
          description: Internal server error.