openapi: 3.0.0
info:
  title: Chatbot API
  version: 1.0.0
  description: API for interacting with the RAG Chatbot embedded in the AI-Native Textbook.

servers:
  - url: /api/chatbot
    description: Chatbot API Base Path

paths:
  /query:
    post:
      summary: Submit a query to the RAG chatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: Optional ID of the authenticated user.
                query_text:
                  type: string
                  description: The user's question.
                  example: "What are the core principles of ROS 2?"
                selected_text:
                  type: string
                  nullable: true
                  description: Optional text selected by the user to provide additional context.
                  example: "ROS 2 is a flexible framework for writing robot software."
              required:
                - query_text
      responses:
        '200':
          description: Successful response with the chatbot's answer.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response_text:
                    type: string
                    description: The chatbot's answer to the query.
                    example: "ROS 2, or Robot Operating System 2, is a set of software libraries and tools that help you build robot applications."
                  session_id:
                    type: string
                    format: uuid
                    description: Unique ID for the chat session.
        '400':
          description: Invalid input.
        '500':
          description: Internal server error.