openapi: 3.0.0
info:
  title: Translation API
  version: 1.0.0
  description: API for translating chapter content into Urdu.

servers:
  - url: /api/translate
    description: Translation API Base Path

paths:
  /{chapter_id}:
    post:
      summary: Translate content for a specific chapter to Urdu
      parameters:
        - name: chapter_id
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier of the chapter to translate.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: ID of the authenticated user.
              required:
                - user_id
      responses:
        '200':
          description: Successfully translated chapter content to Urdu.
          content:
            application/json:
              schema:
                type: object
                properties:
                  chapter_id:
                    type: string
                  translated_content:
                    type: string
                    description: The Urdu translated version of the chapter content.
        '401':
          description: Unauthorized request.
        '404':
          description: Chapter not found.
        '500':
          description: Internal server error.